

class MenuUS11TradingStrategiesGuide:
    SUB_MENU_EN_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                        "div .grid > a[href='https://capital.com/trading-strategies-guide']")
    SUB_MENU_AR_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/ar/trading-strategies-guide']")
    SUB_MENU_BG_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/bg/trading-strategies-guide']")
    SUB_MENU_CS_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/cs/trading-strategies-guide']")
    SUB_MENU_DA_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/da/trading-strategies-guide']")
    SUB_MENU_DE_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/de/trading-strategien-leitfaden']")
    SUB_MENU_ET_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/et/trading-strategies-guide']")
    SUB_MENU_EL_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/el/trading-strategies-guide']")
    # SUB_MENU_ES_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
    #                                         "div .grid > a[href='https://capital.com/es/trading-strategies-guide']")
    SUB_MENU_FR_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/fr/trading-strategies-guide']")
    SUB_MENU_HR_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/hr/trading-strategies-guide']")
    SUB_MENU_IT_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/it/guida-alle-strategie-di-trading']")
    SUB_MENU_LV_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/lv/trading-strategies-guide']")
    SUB_MENU_LT_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/lt/trading-strategies-guide']")
    SUB_MENU_HU_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/hu/trading-strategies-guide']")
    SUB_MENU_ID_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/id/trading-strategies-guide']")
    SUB_MENU_NL_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/nl/trading-strategies-guide']")
    SUB_MENU_PL_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/pl/trading-strategies-guide']")
    SUB_MENU_PT_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/pt/trading-strategies-guide']")
    SUB_MENU_RO_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/ro/trading-strategies-guide']")
    SUB_MENU_RU_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/ru/torgovye-strategii']")
    SUB_MENU_SK_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/sk/trading-strategies-guide']")
    SUB_MENU_SL_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/sl/trading-strategies-guide']")
    SUB_MENU_FI_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/fi/trading-strategies-guide']")
    SUB_MENU_SV_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/sv/trading-strategies-guide']")
    SUB_MENU_VI_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/vi/trading-strategies-guide']")
    SUB_MENU_ZH_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/zh/trading-strategies-guide']")
    SUB_MENU_TH_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/th/trading-strategies-guide']")
    SUB_MENU_CN_TRADING_STRATEGIES_GUIDE = (By.CSS_SELECTOR,
                                            "div .grid > a[href='https://capital.com/cn/trading-strategies-guide']")
